### ISSUE TITLE
Factor viper out of daikin/daikin.go

### ISSUE THREAD

**Issue by cloudkucooland** [redgoose/daikin-one#3]
I'm working on writing a homekit bridge based on your work. Is there any chance you could move daikin/daikin.go into a distinct repo (called github.com/redgoose/go-daikinone) and remove the viper from it? I suggest a New() function that you pass the parameters in, but you choose what works best for you.

I'd rather not simply duplicate the file and make the changes in my own repo. Having a distinct repo for the Daikin logic means that I can contribute to that work without having to worry about stepping on your cli/logger project.

I've written a similar library/tool package for pulling data from my Envoy Solar Panel system

github.com/cloudkucooland/go-envoy
github.com/cloudkucooland/EnvoyCharts

go-envoy is the logic for communicating with the device

EnvoyCharts logs the stats to a database and provides graphing of the data, eerily similar to what you are doing here. I think I'm going to get them to write to the same sqlite DB so I can monitor my electric usage in relation to the Daikin's performance. 

Just my suggestion. Thanks for your work, I'm glad I found this repo before I started my own (I just got the Daikin system this week)

**Comment by redgoose** [comment]
I don't want to split things up, but I have a middle ground I can propose. Before we get that far, I tried to implement a New constructor, but ran into issues. Can you help?

My package:
```
package test

type Test struct {
	ApiKey          string
	IntegratorToken string
	Email           string
}

func New(apiKey string, integratorToken string, email string) *Test {
	t := &Test{
		ApiKey:          apiKey,
		IntegratorToken: integratorToken,
		Email:           email,
	}
	return t
}

func Foo(t *Test) string {
	return "foo"
}
```

The implementing code:
```
t := test.New("", "", "")
t.Foo()
```

`t.Foo()` fails to resolve, and I get this error:

`t.Foo undefined (type *test.Test has no field or method Foo)`

Any ideas what I'm doing wrong?

**Comment by cloudkucooland** [comment]
It's normal go practice to allocate the struct "whole" and return a pointer; two character change--the runtime keeps it in memory until nothing references it anymore (unlike C, which I had to unlearn given I'm an old C hack).

func New(apiKey string, integratorToken string, email string) *Test {
	t := Test{
		ApiKey:          apiKey,
		IntegratorToken: integratorToken,
		Email:           email,
	}
	return &t
}

Then, mark Foo as being a method of Test

func (t * Test) Foo() string {
	return "foo"
}

**Comment by redgoose** [comment]
Oops, that was it, thank you. I had copied the receiver incorrectly. `func Foo(t *Test)` vs your `func (t * Test) Foo()`

Pretty funny we landed on similar implementations for our projects (Go, SQLite, ECharts). I tried using go-echarts but it didn't support multiple Y axes or combined charts (ie. bar and line charts in one) so switched to using ECharts directly. I almost also named my project daikin-charts as well.

I wasn't happy having viper in daikin package so thanks for pointing me in the right direction. I've now removed it, cleaned up the daikin interface, and added error handling instead of using panics.

Going back to your original request, I would like to leave daikin-one as is. When designing it I anticipated someone wanting to reference the daikin package so I left it accessible vs the packages in internal which can't be imported.

In your project you can now import daikin and make use of it like so:

```
package test

import (
	"github.com/redgoose/daikin-one/daikin"
)

func main() {
	d := daikin.New("", "", "")
	locations, err := d.ListDevices()
}
```

Sorry if any of this is obvious to you, I'm new to Go myself.

I know it might be more of a pain to contribute, but I don't foresee much changing in this project as the daikin api is very simplistic (and lacking!). I'll add in the fan and schedule enable/disable functions to the daikin package next to get to 100% api parity.

**Comment by cloudkucooland** [comment]
I've been using go for a few years and really enjoy it. Yeah, go-echarts is a bit limited, but works for my simple purposes. If I get around to trying to find correlations between temperature, daikin operation and solar production I might need a more robust graphing package, but for now it's fine.

Leaving your package as "github.com/redgoose/daikin-one/daikin" is fine. It will be slightly harder for people to find, but not terribly so.

I'll go ahead and build my tool liking to that and make pull requests for you if I need anything added. I also appreciate that you've moved from panic-ing to returning errors. I should be able to control my thermostat with "hey Siri, set the temperature to ..." in no time at all.

**Comment by cloudkucooland** [comment]
{"mode":2,"heatSetpoint":28.9,"coolSetpoint":23.9}
INFO 2023/09/11 21:37:32 device.go:95: update mode setpoint request returned a non-success response: 500 Internal Server Error

I'm able to pull data just fine, but when I try to set, I get either a 500 error.

**Comment by cloudkucooland** [comment]
the docs have the field names unquoted, so I tried that, to no success--I didn't expect it to work, but wanted to test to be sure

https://www.daikinone.com/openapi/documentation/index.html

INFO 2023/09/12 08:09:43 device.go:101: ModeSetpointOptions: {Mode:2 HeatSetpoint:28.9 CoolSetpoint:23.9}
{"mode":2,"heatSetpoint":28.9,"coolSetpoint":23.9}
{
	mode:	2,
	heatSetpoint:	28.9,
	coolSetpoint:	23.9
}
INFO 2023/09/12 08:09:44 device.go:103: update mode setpoint request returned a non-success response: 400 Bad Request

**Comment by redgoose** [comment]
heatSetpoint needs to be less than coolSetpoint. From the [api docs](https://www.daikinone.com/openapi/documentation/index.html):

>  Heat setpoint needs to be lower than the cool setpoint by setpoint delta, and both setpoints need to be between the minimum and maximum setpoint limits.

You can open a new issue and I can add some cli side validation. 
Closing this issue.
